Repository THE-FIRST-DANCE/soomga-frontend, pull requests merged in 2024-02, with the labels that each got.

#18 Feature/#14 플랜메인페이지
  package.json
  src/App.css
  src/App.tsx
  src/Router.tsx
  src/components/icon/Arrow.tsx
  src/components/icon/Star.tsx
  src/components/icon/Time.tsx
  src/components/planner/CreatePlan.tsx
  src/components/planner/Map.tsx
  src/components/planner/PlanItem.tsx
  src/components/planner/PlanList.tsx
  src/components/shared/Button.tsx
  src/index.css
  src/interfaces/plan.ts
  src/pages/PlanPage/index.tsx
  yarn.lock
Labels: ✨ Feature, 🎨 Html&css

#20 Features/#3 header
  package.json
  src/App.tsx
  src/Router.tsx
  src/assets/logo.svg
  src/components/Layout.tsx
  src/components/common/Header.tsx
  src/components/icons/Arrow.tsx
  src/components/icons/HambergIcon.tsx
  src/components/icons/LanguageIcon.tsx
  src/components/icons/LoginIcon.tsx
  src/components/icons/Star.tsx
  src/components/icons/Time.tsx
  src/components/planner/PlanItem.tsx
  src/hooks/useClickOutsideToggle.tsx
  src/index.css
Labels: ✨ Feature, 🎨 Html&css

#21 Feature/#15 plan create
  package.json
  src/Router.tsx
  src/components/icons/Arrow.tsx
  src/components/icons/Cancel.tsx
  src/components/planner/CreatePlan.tsx
  src/components/planner/CreatePlanModal.tsx
  src/components/shared/Modal.tsx
  src/data/region.ts
  src/hooks/useCreatePlan.tsx
  src/main.tsx
  src/pages/PlanCreatePage/index.tsx
  src/recoil/atoms/PlanInfo.ts
  yarn.lock
Labels: ✨ Feature, 🎨 Html&css

#24 Feature/#5 top video
  src/App.tsx
  src/Router.tsx
  src/components/common/Header.tsx
  src/components/home/MainVideo.tsx
  src/components/icons/HambergIcon.tsx
  src/components/icons/LanguageIcon.tsx
  src/components/icons/LoginIcon.tsx
  src/index.css
  src/pages/home/index.tsx
  yarn.lock
Labels: ✨ Feature, 🎨 Html&css

#26 Feature/#6 recommended regions
  src/App.tsx
  src/assets/busan.png
  src/assets/geoje.png
  src/assets/logo_noLetter.svg
  src/assets/seoul.png
  src/assets/ulsan.png
  src/components/home/RecommendedRegions.tsx
  src/index.css
  src/pages/home/index.tsx
Labels: ✨ Feature, 🎨 Html&css

#28 Feature/#7 mapOfKorea
  src/components/planner/Map.tsx
  src/pages/home/index.tsx
Labels: ✨ Feature, 🎨 Html&css

#29 Feature/#16 plan place
  package.json
  src/api/PlanAPI.ts
  src/components/icons/Check.tsx
  src/components/icons/Plus.tsx
  src/components/icons/Search.tsx
  src/components/planner/CreatePlanModal.tsx
  src/components/planner/GoogleMap.tsx
  src/components/planner/PlanOrder.tsx
  src/components/planner/PlanOrderItem.tsx
  src/components/planner/place/PlaceAdd.tsx
  src/components/planner/place/PlaceAddItem.tsx
  src/components/planner/place/PlaceAddModal.tsx
  src/components/planner/place/PlaceItem.tsx
  src/components/planner/place/PlaceSelect.tsx
  src/components/planner/place/PlaceTab.tsx
  src/components/shared/Input.tsx
  src/data/region.ts
  src/hooks/useCalcurateTotalTime.tsx
  src/hooks/useCreatePlan.tsx
  src/hooks/useSubstring.tsx
  src/hooks/useTimeDifference.tsx
  src/interfaces/plan.ts
  src/main.tsx
  src/pages/PlanCreatePage/index.tsx
  src/pages/PlanPage/index.tsx
  src/recoil/atoms/PlanInfo.ts
  src/recoil/atoms/PlanList.ts
  yarn.lock
Labels: 📬 API, ✨ Feature, 🎨 Html&css

#31 Feature/#9 recommend regions
  src/assets/main_leftImg.png
  src/assets/main_leftLetter.svg
  src/components/home/MainVideo.tsx
  src/components/home/SRecommendedRegions.tsx
  src/components/home/URecommendedRegions.tsx
  src/components/planner/GoogleMap.tsx
  src/pages/home/index.tsx
Labels: ✨ Feature, 🎨 Html&css

#32 Feature/#30 place detail confirm
  package.json
  src/components/planner/CreatePlanModal.tsx
  src/components/planner/PlanOrder.tsx
  src/components/planner/PlanOrderItem.tsx
  src/components/planner/SelectTransportation.tsx
  src/components/planner/place/PlaceAddModal.tsx
  src/components/planner/place/PlaceDetail.tsx
  src/components/planner/place/PlaceItem.tsx
  src/components/planner/place/PlaceSelect.tsx
  src/components/planner/place/PlaceTab.tsx
  src/components/shared/Button.tsx
  src/components/shared/Modal.tsx
  src/components/shared/Spinner.tsx
  src/hooks/useCreatePlan.tsx
  src/interfaces/plan.ts
  src/pages/PlanConfirm/index.tsx
  src/recoil/atoms/PlanList.ts
  yarn.lock
Labels: ✨ Feature, 🎨 Html&css, 🔨 Refactor

#34 Feature/#10 regions carousel
  package.json
  src/components/home/RegionCarousel.tsx
  src/components/home/URecommendedRegions.tsx
  src/components/planner/GoogleMap.tsx
  src/pages/home/index.tsx
  yarn.lock
Labels: ✨ Feature, 🎨 Html&css

#35 Feature/#11 comment carousel
  src/components/home/CommentCarousel.tsx
  src/components/home/RegionCarousel.tsx
  src/pages/home/index.tsx
Labels: ✨ Feature, 🎨 Html&css

#36 Feature/#12 chating btn
  src/assets/chatBtn.svg
  src/components/home/ChatButton.tsx
  src/components/home/CommentCarousel.tsx
  src/pages/home/index.tsx
Labels: ✨ Feature, 🎨 Html&css

#43 Feature/#17 place confirm
  src/Router.tsx
  src/api/PlanAPI.ts
  src/components/planner/CreatePlanModal.tsx
  src/components/planner/GoogleMap.tsx
  src/components/planner/PlanConfirmItem.tsx
  src/components/planner/PlanLeftTab.tsx
  src/components/planner/PlanOrder.tsx
  src/components/planner/PlanOrderItem.tsx
  src/components/planner/SelectTransportation.tsx
  src/components/planner/place/PlaceDetail.tsx
  src/components/planner/place/PlaceItem.tsx
  src/components/planner/place/PlaceSelect.tsx
  src/components/shared/FullLoading.tsx
  src/hooks/useCreatePlan.tsx
  src/interfaces/plan.ts
  src/pages/PlanConfirm/index.tsx
  src/pages/PlanCreatePage/index.tsx
  src/recoil/atoms/PlanInfo.ts
  src/recoil/atoms/PlanList.ts
Labels: 📬 API, 🐞 BugFix, ✨ Feature, 🎨 Html&css, 🔨 Refactor

#44 Feature/#40 list of guides
  src/Router.tsx
  src/assets/flag.svg
  src/assets/flag2.svg
  src/assets/userImage.svg
  src/components/guide/GuidePage.tsx
  src/components/guide/leftSection/CheckboxComponent.tsx
  src/components/guide/leftSection/GenderFakeCheckbox.tsx
  src/components/guide/leftSection/GuidePageUtils.tsx
  src/components/guide/leftSection/RangeComponent.tsx
  src/components/guide/leftSection/RatingFakeCheckbox.tsx
  src/components/guide/rightSection/GuideCard.tsx
  src/components/home/MagnifieirIcon.tsx
Labels: ✨ Feature, 🎨 Html&css, 🔨 Refactor

#46 Feature/#45 detail of guide
  package.json
  src/Router.tsx
  src/assets/caution.svg
  src/assets/guideImg.png
  src/components/guide/list/leftSection/CheckboxComponent.tsx
  src/components/guide/list/leftSection/GenderFakeCheckbox.tsx
  src/components/guide/list/leftSection/GuidePageUtils.tsx
  src/components/guide/list/leftSection/RangeComponent.tsx
  src/components/guide/list/leftSection/RatingFakeCheckbox.tsx
  src/components/guide/list/rightSection/GuideCard.tsx
  src/components/icons/Arrow.tsx
  src/components/icons/AuthIcon.tsx
  src/components/icons/CarIcon.tsx
  src/components/icons/CautionIcon.tsx
  src/components/icons/ChatIcon.tsx
  src/components/icons/CircleCheck.tsx
  src/components/icons/Comunication.tsx
  src/components/icons/FollowIcon.tsx
  src/components/icons/InstagramIcon.tsx
  src/components/icons/Location.tsx
  src/components/icons/Time.tsx
  src/components/icons/XIcon.tsx
  src/components/icons/follow.svg
  src/pages/guide/detail.tsx
  src/pages/guide/index.tsx
  src/pages/home/index.tsx
  yarn.lock
Labels: ✨ Feature, 🎨 Html&css

#47 Feature/#41 plan edit
  package.json
  src/api/PlanAPI.ts
  src/components/planner/Map.tsx
  src/components/planner/PlanConfirmItem.tsx
  src/components/planner/PlanEdit.tsx
  src/components/planner/PlanEditItem.tsx
  src/components/planner/PlanItem.tsx
  src/components/planner/PlanLeftTab.tsx
  src/components/planner/PlanList.tsx
  src/components/planner/PlanOrder.tsx
  src/components/planner/PlanOrderItem.tsx
  src/components/planner/SelectTransportation.tsx
  src/components/planner/place/PlaceAdd.tsx
  src/components/planner/place/PlaceAddModal.tsx
  src/components/planner/place/PlaceEditAddItem.tsx
  src/components/planner/place/PlaceItem.tsx
  src/components/planner/place/PlaceSelect.tsx
  src/components/planner/place/PlaceTab.tsx
  src/hooks/useCalcurateTotalTime.tsx
  src/hooks/useCreatePlan.tsx
  src/interfaces/plan.ts
  src/pages/PlanConfirm/index.tsx
  src/pages/PlanCreatePage/index.tsx
  src/pages/PlanPage/index.tsx
  src/recoil/atoms/PlanList.ts
  src/state/store/PlanInfo.ts
  src/state/store/PlanList.ts
  yarn.lock
Labels: 📬 API, ✨ Feature, 🎨 Html&css, 🔨 Refactor

#48 refactor: 안쓰는 타입, 리코일 정리 및 주석 작업
  src/components/planner/PlanConfirmItem.tsx
  src/components/planner/PlanEdit.tsx
  src/components/planner/PlanEditItem.tsx
  src/components/planner/PlanItem.tsx
  src/components/planner/PlanOrder.tsx
  src/components/planner/PlanOrderItem.tsx
  src/components/planner/place/PlaceAdd.tsx
  src/components/planner/place/PlaceAddItem.tsx
  src/components/planner/place/PlaceAddModal.tsx
  src/components/planner/place/PlaceItem.tsx
  src/interfaces/plan.ts
  src/main.tsx
  src/state/store/PlanList.ts
Labels: 🔨 Refactor

#49 Feature/#37 login page
  package.json
  src/App.tsx
  src/Router.tsx
  src/api/LoginSignUp.ts
  src/assets/loginLogo.png
  src/components/common/Header.tsx
  src/components/home/ChatButton.tsx
  src/components/home/CommentCarousel.tsx
  src/components/home/RegionCarousel.tsx
  src/components/home/URecommendedRegions.tsx
  src/components/icons/GoogleIcon.tsx
  src/components/icons/LanguageIcon.tsx
  src/components/icons/LineIcon.tsx
  src/components/loginAndsignup/UserForm.login.style.tsx
  src/components/loginAndsignup/UserForm.tsx
  src/hooks/useAccessToken.tsx
  src/interfaces/icon.ts
  src/main.tsx
  src/pages/guide/detail.tsx
  src/pages/home/index.tsx
  src/pages/login/index.tsx
  src/pages/login/loginSignup.style.tsx
  src/pages/redirect/index.tsx
  src/recoil/AccessTokenAtom.ts
  src/utils/cookie.tsx
  src/utils/oauth.connector.ts
  src/utils/validationSchema.tsx
  yarn.lock
Labels: 📬 API, ✨ Feature, 🎨 Html&css, 🔨 Refactor
