Repository THE-FIRST-DANCE/soomga-frontend, pull requests merged in 2024-04, with the labels that each got.

#78 Feature/#74 data binding
  .http
  src/Router.tsx
  src/api/GuidePageAPI.ts
  src/api/LoginSignUp.ts
  src/components/common/Header.tsx
  src/components/guide/list/leftSection/GuidePageUtils.tsx
  src/components/guide/list/leftSection/RangeComponent.tsx
  src/components/guide/list/rightSection/GuideCard copy.tsx
  src/components/guide/list/rightSection/GuideCard.tsx
  src/components/home/CommentCarousel.tsx
  src/components/home/MagnifieirIcon.tsx
  src/components/home/URecommendedRegions.tsx
  src/components/icons/AuthIcon.tsx
  src/components/icons/CircleCheck.tsx
  src/components/icons/Comunication.tsx
  src/components/icons/Location.tsx
  src/components/icons/XIcon.tsx
  src/components/myPageCommon/BasicInfo.tsx
  src/components/myPageCommon/Following.tsx
  src/components/myPageCommon/Guide.tsx
  src/components/myPageCommon/LeftInfo.tsx
  src/components/myPageCommon/Planing.tsx
  src/components/myPageCommon/PostCard.tsx
  src/components/myPageCommon/RequestGuide.tsx
  src/components/myPageCommon/Review.tsx
  src/components/myPageCommon/index.tsx
  src/hooks/useObserver.tsx
  src/interfaces/guideInfo.ts
  src/interfaces/requestParams.ts
  src/pages/guide/detail.tsx
  src/pages/guide/index.tsx
  src/pages/home/index.tsx
  src/pages/login/index.tsx
  src/pages/recommendationPage/detail.tsx
  src/state/store/SelecteddatasAtom.ts
  src/utils/oauth.connector.ts
Labels: 📬 API, 🐞 BugFix, ✨ Feature, 🎨 Html&css

#81 Feature/#79 plan refactor
  package.json
  src/App.tsx
  src/Router.tsx
  src/api/PlanAPI.ts
  src/components/icons/Heart.tsx
  src/components/icons/Search.tsx
  src/components/icons/View.tsx
  src/components/planner/PlanConfirmItem.tsx
  src/components/planner/PlanDetailItem.tsx
  src/components/planner/PlanEdit.tsx
  src/components/planner/PlanItem.tsx
  src/components/planner/PlanLeftTab.tsx
  src/components/planner/PlanOrder.tsx
  src/components/planner/PlanOrderItem.tsx
  src/components/planner/place/PlaceAdd.tsx
  src/components/planner/place/PlaceAddItem.tsx
  src/components/planner/place/PlaceAddModal.tsx
  src/components/planner/place/PlaceItem.tsx
  src/components/planner/place/PlaceSelect.tsx
  src/components/planner/place/PlaceTab.tsx
  src/hooks/plan/usePlanConfirm.tsx
  src/hooks/useDebounce.tsx
  src/interfaces/guideInfo.ts
  src/interfaces/plan.ts
  src/pages/PlanConfirm/index.tsx
  src/pages/PlanDetailPage/index.tsx
  src/pages/PlanDetailPage/tab.tsx
  src/pages/schedulePage/index.tsx
  yarn.lock
Labels: 🐞 BugFix, ✨ Feature, 🎨 Html&css

#84 🏗️ build: 빌드를 위한 룰 수정, 일부 코드 에러 수정
  Dockerfile
  nginx.conf
  package.json
  src/components/chat/Chatting.tsx
  src/components/guide/list/rightSection/GuideCard copy.tsx
  src/components/icons/Star.tsx
  src/components/myPageCommon/Following.tsx
  src/components/myPageCommon/Guide.tsx
  src/components/myPageCommon/Planing.tsx
  src/components/myPageCommon/Posting.tsx
  src/components/myPageCommon/Review.tsx
  src/components/planner/PlanConfirmItem.tsx
  src/components/planner/SelectTransportation.tsx
  src/components/recommendations/CommentLayout.tsx
  src/pages/guide/detail.tsx
  tsconfig.json
  vite.config.ts
  yarn.lock
Labels: 🐞 BugFix, 🌏 Deploy
