Repository THE-FIRST-DANCE/soomga-frontend, pull requests merged in 2024-03, with the labels that each got.

#51 Feature/#50 itinerary page
  src/Router.tsx
  src/components/itineraryCalendar/Calendar.tsx
  src/components/itineraryCalendar/ScheduleList.tsx
  src/components/loginAndsignup/UserForm.tsx
  src/pages/guide/detail.tsx
  src/pages/itinerary/index.tsx
  src/recoil/MonthAtom.ts
Labels: ✨ Feature, 🎨 Html&css, 🔨 Refactor

#53 Feature/#52 hot posts
  src/Router.tsx
  src/components/recommendations/RecommedCard.tsx
  src/pages/itinerary/index.tsx
  src/pages/recommendationPage/index.tsx
  src/pages/recommendationPage/regionslist.tsx
Labels: ✨ Feature, 🎨 Html&css

#58 Feature/#55 calendar add
  package.json
  src/api/PlanAPI.ts
  src/pages/schedulePage/index.tsx
  yarn.lock
Labels: 🐞 BugFix, ✨ Feature, 🎨 Html&css

#59 Feature/#57 post crud
  package.json
  src/Router.tsx
  src/components/react-quill/QuillEditor.tsx
  src/components/recommendations/PageNation.tsx
  src/components/recommendations/PostCreate.tsx
  src/components/recommendations/PostEdit.tsx
  src/pages/recommendationPage/regionslist.tsx
  yarn.lock
Labels: ✨ Feature, 🎨 Html&css

#61 Feature/#55 calendar add
  package.json
  src/Router.tsx
  src/api/EventAPI.ts
  src/api/PlanAPI.ts
  src/components/icons/Delete.tsx
  src/components/icons/Description.tsx
  src/components/icons/Edit.tsx
  src/components/schedule/CustomToolbar.tsx
  src/components/schedule/DescriptionEditor.tsx
  src/components/schedule/ScheduleCreateModal.tsx
  src/components/schedule/ScheduleDetailModal.tsx
  src/components/schedule/SetDateCalendar.tsx
  src/components/schedule/TimeSection.tsx
  src/interfaces/event.ts
  src/pages/schedulePage/index.tsx
  src/utils/timeSlots.ts
  yarn.lock
Labels: 📬 API, ✨ Feature, 🎨 Html&css

#65 Feature/#60 chatting
  .eslintrc.cjs
  src/components/chat/Chatting.tsx
  src/components/common/Header.tsx
  src/components/home/ChatButton.tsx
  src/components/icons/ImageIcon.tsx
  src/components/icons/Search.tsx
  src/components/recommendations/RecommedCard.tsx
  src/hooks/useClickOutsideToggle.tsx
  src/pages/home/index.tsx
  src/pages/recommendationPage/index.tsx
Labels: 🐞 BugFix, ✨ Feature, 🎨 Html&css

#68 Feature/#66 event plan
  src/Router.tsx
  src/api/PlanAPI.ts
  src/components/schedule/ScheduleCreateModal.tsx
  src/components/schedule/ScheduleDetailModal.tsx
  src/components/schedule/SchedulePlans.tsx
  src/hooks/event/useEventForm.tsx
  src/interfaces/event.ts
Labels: 📬 API, ✨ Feature, 🎨 Html&css

#69 Feature/#67 common my page
  src/Router.tsx
  src/components/chat/Chatting.tsx
  src/components/common/Header.tsx
  src/components/myPageCommon/BasicInfo.tsx
  src/components/myPageCommon/Following.tsx
  src/components/myPageCommon/LeftInfo.tsx
  src/components/myPageCommon/MainContainer.tsx
  src/components/myPageCommon/Planing.tsx
  src/components/myPageCommon/PostCard.tsx
  src/components/myPageCommon/Posting.tsx
  src/components/myPageCommon/Review.tsx
  src/components/myPageCommon/index.tsx
  src/components/recommendations/RecommedCard.tsx
  src/pages/guide/detail.tsx
  src/pages/recommendationPage/detail.tsx
Labels: ✨ Feature, 🎨 Html&css

#71 Feature/#70 guide mypage
  src/components/common/Header.tsx
  src/components/icons/InstagramIcon.tsx
  src/components/icons/XIcon.tsx
  src/components/myPageCommon/Guide.tsx
  src/components/myPageCommon/MainContainer.tsx
  src/components/myPageCommon/Planing.tsx
  src/components/myPageCommon/index.tsx
  src/pages/guide/detail.tsx
  src/pages/guide/index.tsx
Labels: 🐞 BugFix, ✨ Feature, 🎨 Html&css

#73 Feature/#70 guide mypage
  src/Router.tsx
  src/components/myPageCommon/LeftInfo.tsx
  src/components/myPageCommon/MainContainer.tsx
  src/components/myPageCommon/RequestGuide.tsx
  src/components/myPageCommon/index.tsx
  src/state/store/RequestGuide.ts
Labels: ✨ Feature, 🎨 Html&css
